-- =============================================================================
-- Keldra: per-task email threading (Zoho-desk style).
--
-- Run this ONCE in the Supabase SQL editor (project fmeixgnxkcapxyhrjhvm),
-- AFTER supabase-org-model.sql. Idempotent + safe to re-run.
--
-- DESIGN NOTE — there is no persisted `tasks` table in this app (tasks are
-- client-side seed data keyed by a task CODE like "ELE-COLO-1030"). So instead
-- of "columns on the task table", a thread is anchored by (org_id, task_code)
-- in task_threads, which holds the email_token. Everything is org-scoped via
-- RLS with the standard superadmin carve-out.
--
-- ADDRESS ENCODING — the threadable reply-to is
--     task-{threadHex}-{email_token}@reply.keldra.io
-- where threadHex is the thread UUID with hyphens stripped (32 hex chars) and
-- email_token is hex. Hex avoids the hyphen/underscore collisions that would
-- break parsing, because task codes themselves contain hyphens.
-- =============================================================================

create extension if not exists pgcrypto with schema extensions;

-- 1. THREADS — one per (org, task code). email_token is generated by the app on
--    first send; the column is unique so a token maps to exactly one thread.
create table if not exists public.task_threads (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organisations(id) on delete cascade,
  task_code   text not null,
  email_token text not null unique,
  created_at  timestamptz not null default now(),
  unique (org_id, task_code)
);
create index if not exists task_threads_org_task_idx on public.task_threads(org_id, task_code);

-- 2. EMAILS — outbound + inbound, both rendered in the task Activity trail.
create table if not exists public.task_emails (
  id              uuid primary key default gen_random_uuid(),
  thread_id       uuid not null references public.task_threads(id) on delete cascade,
  org_id          uuid not null references public.organisations(id) on delete cascade,
  task_code       text not null,
  direction       text not null check (direction in ('outbound','inbound')),
  from_email      text,
  to_email        text,
  subject         text,
  body_text       text,
  body_html       text,
  resend_email_id text,
  message_id      text,
  in_reply_to     text,
  actor_user_id   uuid references auth.users(id),
  created_at      timestamptz not null default now()
);
create index if not exists task_emails_thread_idx   on public.task_emails(thread_id);
create index if not exists task_emails_org_task_idx on public.task_emails(org_id, task_code);

-- 3. ATTACHMENTS — metadata; bytes live in the private storage bucket below.
create table if not exists public.task_email_attachments (
  id           uuid primary key default gen_random_uuid(),
  email_id     uuid not null references public.task_emails(id) on delete cascade,
  org_id       uuid not null references public.organisations(id) on delete cascade,
  filename     text,
  content_type text,
  size_bytes   int,
  storage_path text not null,
  created_at   timestamptz not null default now()
);
create index if not exists task_email_attachments_email_idx on public.task_email_attachments(email_id);

-- 4. DEAD-LETTER — inbound mail we couldn't match to a thread (bad/tampered
--    token, unknown task). Nothing silently disappears.
create table if not exists public.inbound_unmatched (
  id         uuid primary key default gen_random_uuid(),
  to_email   text,
  from_email text,
  subject    text,
  reason     text,
  raw        jsonb,
  created_at timestamptz not null default now()
);
create index if not exists inbound_unmatched_created_idx on public.inbound_unmatched(created_at desc);

-- 5. GRANTS (table-level; RLS still restricts rows). Writes happen via the
--    SERVICE ROLE (send route + inbound webhook), which bypasses RLS, so
--    authenticated users only need SELECT.
grant select on public.task_threads           to authenticated;
grant select on public.task_emails            to authenticated;
grant select on public.task_email_attachments to authenticated;
grant select on public.inbound_unmatched      to authenticated;

-- 6. RLS — org members + superadmin can READ their org's threads/emails.
alter table public.task_threads           enable row level security;
alter table public.task_emails            enable row level security;
alter table public.task_email_attachments enable row level security;
alter table public.inbound_unmatched      enable row level security;

drop policy if exists task_threads_select on public.task_threads;
create policy task_threads_select on public.task_threads for select to authenticated
  using (public.is_superadmin() or org_id = public.auth_org_id());

drop policy if exists task_emails_select on public.task_emails;
create policy task_emails_select on public.task_emails for select to authenticated
  using (public.is_superadmin() or org_id = public.auth_org_id());

drop policy if exists task_email_attachments_select on public.task_email_attachments;
create policy task_email_attachments_select on public.task_email_attachments for select to authenticated
  using (public.is_superadmin() or org_id = public.auth_org_id());

-- Dead-letter is platform-level (no org) → superadmin only.
drop policy if exists inbound_unmatched_select on public.inbound_unmatched;
create policy inbound_unmatched_select on public.inbound_unmatched for select to authenticated
  using (public.is_superadmin());

-- 7. PRIVATE STORAGE BUCKET for inbound attachments. Signed URLs are minted
--    server-side, but we also scope direct object reads to the owning org
--    (path = {org_id}/{task_code}/{email_id}/{filename}).
insert into storage.buckets (id, name, public)
values ('task-email-attachments', 'task-email-attachments', false)
on conflict (id) do nothing;

drop policy if exists task_attachments_read on storage.objects;
create policy task_attachments_read on storage.objects for select to authenticated
  using (
    bucket_id = 'task-email-attachments'
    and (
      public.is_superadmin()
      or (storage.foldername(name))[1] = public.auth_org_id()::text
    )
  );

-- 8. SENDER MATCHING — let the inbound webhook (service role) resolve an
--    inbound sender's email to a known auth user, to attribute the comment.
--    SECURITY DEFINER to read auth.users; service-role only (no anon/auth grant).
create or replace function public.user_id_by_email(p_email text)
returns uuid language sql stable security definer set search_path = public, auth as $$
  select id from auth.users where lower(email) = lower(p_email) limit 1
$$;
revoke all on function public.user_id_by_email(text) from public, anon, authenticated;

-- 9. SANITY OUTPUT ------------------------------------------------------------
select 'task_threads'     as table, count(*)::text as rows from public.task_threads
union all select 'task_emails',      count(*)::text from public.task_emails
union all select 'inbound_unmatched', count(*)::text from public.inbound_unmatched;
